"""initial migration

Revision ID: 143e2547edcb
Revises: 641b310fd621
Create Date: 2019-12-04 14:38:26.584842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143e2547edcb'
down_revision = '641b310fd621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
