"""initial migration

Revision ID: a3ca44ec5d9a
Revises: 143e2547edcb
Create Date: 2019-12-05 16:26:05.082945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ca44ec5d9a'
down_revision = '143e2547edcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title_html')
    # ### end Alembic commands ###
