"""initial migration

Revision ID: ebee16d9e6bd
Revises: c05af9f7b09e
Create Date: 2019-07-04 22:51:31.197382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebee16d9e6bd'
down_revision = 'c05af9f7b09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mytest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mytest')
    # ### end Alembic commands ###
